services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    container_name: recommendarr
    ports:
      - "3003:3000"  # <-- host:container
    volumes:
      - /srv/docker-data/recommendarr:/app/server/data
    environment:
      - NODE_ENV=production
      - PORT=3000  # <-- maradjon 3000
      - PUBLIC_URL=http://192.168.0.YOUR_DOCKER_IP:3003
      - OLLAMA_URL=http://192.168.0.YOUR_PC_IP:11434
    restart: unless-stopped
    networks:
      - arr_stack

  suggestarr:
    image: ciuse99/suggestarr:latest
    container_name: suggestarr
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Bratislava
      - LOG_LEVEL=info
      - SUGGESTARR_PORT=5000
    restart: unless-stopped
    volumes:
      - /srv/docker-data/suggestarr:/app/config/config_files
    networks:
      - arr_stack

networks:
  arr_stack:
    external: true
