services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    environment:
      - TZ=${TZ}
    ports:
      - 9705:9705
    volumes:
      - /srv/docker-data/huntarr:/config
    restart: unless-stopped
networks:
  arr_stack:
    external: true
